<?php

namespace common\models;

use Yii;
use yii\db\ActiveRecord;
use yii\web\UploadedFile;

/**
 * @property int $id
 * @property string $name
 * @property string $type
 * @property string|null $file
 * @property int $active
 */
class DanhMuc extends ActiveRecord
{
    const TU_KHOA = 'Từ khóa';
    const THUONG_HIEU = 'Thương hiệu';
    const LOAI_SAN_PHAM = 'Loại sản phẩm';

    public $file_name;

    public static function listCategory(){
        return [
            self::TU_KHOA => '<span class="text-danger">Từ Khóa</span>',
            self::THUONG_HIEU => '<span class="text-primary">Thương hiệu</span>',
            self::LOAI_SAN_PHAM => '<span class="text-success">Loại sản phẩm</span>',
        ];
    }

    public static function tableName()
    {
        return '{{%danh_muc}}';
    }

    public function rules()
    {
        return [
            [['name'], 'required', 'message' => '{attribute} không được để trống'],
            [['type', 'file'], 'string'],
            [['name'], 'string', 'max' => 50],
            [['active'], 'integer'],
            [['file_name'], 'safe'],
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Tên',
            'type' => 'Phân loại',
            'file' => 'File',
            'active' => 'Trạng thái',
            'file_name' => 'Ảnh đại diện',
        ];
    }

    public function beforeSave($insert)
    {
        if($this->type === DanhMuc::THUONG_HIEU) {
            $file = UploadedFile::getInstance($this, 'file_name');
            if (is_null($file)) {
                $this->file = 'no-image.jpg';
            } else {
                $name_file = time() . '_' . myAPI::createCode($this->name) . '-logo' . myAPI::get_extension_image($file->type);
                $this->file = $name_file;
                if(!$insert){
                    $old_thuong_hieu = DanhMuc::findOne($this->id);
                    if($old_thuong_hieu->file !== 'no-image.jpg'){
                        Yii::$app->session->set('old_image', $old_thuong_hieu->file);
                    }
                }
            }
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        if($this->type === DanhMuc::THUONG_HIEU) {
            $file = UploadedFile::getInstance($this, 'file_name');
            if (!is_null($file)) {
                $path = dirname(dirname(__DIR__)).'/images/thuong-hieu/'.$this->file;
                $file->saveAs($path);
                if(!$insert){
                    if(isset(Yii::$app->session['old_image'])) {
                        $old_thuong_hieu = Yii::$app->session->get('old_image');
                        $path = dirname(dirname(__DIR__)).'/images/thuong-hieu/'.$old_thuong_hieu;
                        if(is_file($path)){
                            unlink($path);
                        }
                        unset(Yii::$app->session['old_image']);
                    }
                }
            }
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
