<?php
namespace common\models;

use yii\db\ActiveRecord;

class myActiveRecord extends ActiveRecord
{
    public function beforeSave($insert)
    {
        if (in_array('code', self::attributes()) && in_array('name', self::attributes())) {
            $this->name = trim($this->name);
            $this->code = myAPI::createCode(self::getAttribute("name"));
        }
        if ($insert) {
            if (in_array('created_at', self::attributes())) {
                $this->created_at = date("Y-m-d H:i:s");
            }
            if (in_array('user_created_id', self::attributes())) {
                if (!\Yii::$app->user->isGuest) {
                    $this->user_created_id = \Yii::$app->user->id;
                }
            }
            if (in_array('user_created', self::attributes())) {
                if (!\Yii::$app->user->isGuest) {
                    $this->user_created = \Yii::$app->user->identity->username;
                }
            }
        } else {
            if (in_array('updated_at', self::attributes())) {
                $this->updated_at = date("Y-m-d H:i:s");
            }
            if (in_array('user_created_id', self::attributes())) {
                if(!\Yii::$app->user->isGuest) {
                    $this->user_updated_id = \Yii::$app->user->id;
                }
            }
            if (in_array('user_updated', self::attributes())) {
                if (!\Yii::$app->user->isGuest) {
                    $this->user_updated = \Yii::$app->user->identity->username;
                }
            }
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
