<?php

namespace common\models;

use Yii;
use yii\db\ActiveRecord;

/**
 * @property int $id
 * @property string|null $name
 * @property string|null $effect_day
 * @property string|null $file
 */
class Note extends ActiveRecord
{
    public static function tableName()
    {
        return '{{%note}}';
    }

    public function rules()
    {
        return [
            [['effect_day'], 'safe'],
            [['file'], 'string'],
            [['name'], 'string', 'max' => 100],
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'effect_day' => 'Effect Day',
            'file' => 'File',
        ];
    }

    public function beforeSave($insert)
    {
        $this->effect_day = myAPI::convertDateSaveIntoDb($this->effect_day);

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterDelete()
    {
        $path = dirname(dirname(__DIR__)) . '/uploads/' . $this->file;
        if(is_file($path)){
            unlink($path);
        }

        parent::afterDelete(); // TODO: Change the autogenerated stub
    }
}
