<?php

namespace common\models;

use Yii;

/**
 * @property int $id
 * @property string|null $file
 * @property int|null $slider_id
 *
 * @property Slider $slider
 */
class PictureSlider extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return 'picture_slider';
    }

    public function rules()
    {
        return [
            [['file'], 'string'],
            [['slider_id'], 'integer'],
            [['slider_id'], 'exist', 'skipOnError' => true, 'targetClass' => Slider::className(), 'targetAttribute' => ['slider_id' => 'id']],
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'file' => 'File',
            'slider_id' => 'Slider ID',
        ];
    }

    public function getSlider()
    {
        return $this->hasOne(Slider::className(), ['id' => 'slider_id']);
    }

    public function beforeDelete()
    {
        $path = dirname(dirname(__DIR__)).'/images/slider/'.$this->file;
        if(is_file($path)){
            unlink($path);
        }

        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
