<?php

namespace common\models;

use Yii;
use common\models\myAPI;
use yii\web\UploadedFile;
use yii\helpers\FileHelper;

/**
 * @property int $id
 * @property string|null $title
 * @property string|null $content
 * @property string|null $link
 * @property string|null $presentation
 *
 * @property PictureSlider[] $pictureSliders
 */
class Slider extends \yii\db\ActiveRecord
{
    public $pictures;

    public static function tableName()
    {
        return 'slider';
    }

    public function rules()
    {
        return [
            [['content', 'link'], 'string'],
            [['title'], 'string', 'max' => 100],
            [['pictures'], 'safe'],
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Tiêu đề',
            'content' => 'Nội dung',
            'link' => 'Link',
            'pictures' => 'Ảnh slider',
        ];
    }

    public function getPictureSliders()
    {
        return $this->hasMany(PictureSlider::className(), ['slider_id' => 'id']);
    }

    public function beforeDelete()
    {
        foreach ($this->pictureSliders as $pictureSlider) {
            $pictureSlider->delete();
        }

        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $files = UploadedFile::getInstances($this, 'pictures');
        if (!empty($files)) {
            foreach ($files as $key => $file) {
                $path = dirname(dirname(__DIR__)) . '/images/slider/' . date('Y/m/d');
                $link = $path . $path . '/' . $key . '_' . myAPI::createCode($this->title) . myAPI::get_extension_image($file->type);

                if (FileHelper::createDirectory($path, $mode = 0775, $recursive = true)) {
                    $file->saveAs($path . '/' . $key . '_' . myAPI::createCode($this->title) . myAPI::get_extension_image($file->type));
                }
            }
        }

        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
